#!/usr/bin/env python3

import click
import sys
from berlin.backend_dict import BackendDict
from berlin.commands import CommandHandler

@click.group(invoke_without_command=True)
@click.pass_context
def cli(ctx):
    click.echo("""
berliner   Z 9001
-----------------
Wilkommen, bienvenue, welcome. Come on in!

OS
    """.strip())

    if ctx.invoked_subcommand is None:
        interactive()

@cli.command()
def consistency(self):
    interactive('CONSISTENCY')

def interactive(command=None):
    state_dict, subdiv_dict, locode_dict = load()

    handler = CommandHandler(state_dict, subdiv_dict, locode_dict, printer=click.echo)
    if command:
        click.echo("> ", nl=False)
        handler.run(command)
    else:
        line = ""
        while line != "QUIT":
            line = input("> ").strip().split(' ')
            command, arguments = line[0], line[1:]
            handler.run(command, *arguments)
            click.echo()

def load():
    data_sources = {
        'state_file': 'data/locode/un-locode/data/country-codes.csv',
        'subdiv_file': 'data/locode/un-locode/data/subdivision-codes.csv',
        'locode_file': 'data/locode/un-locode/data/code-list-sdn.csv'
    }

    backend = BackendDict()

    return backend.retrieve(data_sources)


if __name__ == '__main__':
    cli()
